easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: "email" }
          - { property: "username" }
          - { property: "Roles", type: 'collection'}
      list:
        actions:
          - { name: "edit",icon: "pencil",label: false, css_class: "btn btn-primary mb-1"}
          - { name: "delete",icon: "trash",label: false,css_class: "btn btn-danger"}  